version: '3'
services:
  mkdocs:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    command: mkdocs serve --dev-addr=0.0.0.0:8000
